name: Octonav

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [5.0.100]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Run dotnet restore
      run: dotnet restore
    - name: Run octonav
      run: dotnet octonav --solution ionide-proj-info.sln --repository ${{ github.repository }} --ref ${{ github.ref }} --sha ${{ github.sha }} --userkey ${{ secrets.OCTONAVKEY }}
